# Site settings
description: An index of ROS Robots
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
url: "http://robots.ros.org" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Lorem Ipsum
user_description: Anon Developer at Lorem Ipsum Dolor
user_title: ROS Robots
email: ros@osrfoundation.org
twitter_username: rosorg
github_username:  ros
gplus_username:  rosorg
disqus_username: lorem_ipsum

featured_robot: TurtleBot

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
# TODO(tfoote) add Categories
links:
  - title: Home
    url: /
  - title: All
    url: /all
  - title: Tags
    url: /tags
  - title: About
    url: /about
  - title: Contributing
    url: /contributing
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules', 'template_post.em']
